### ISSUE TITLE
2.0.0.33 f-droid crashes (de.sudoq.controller.menus.preferences.LanguageSetting.setLanguage)

### ISSUE THREAD

**Issue by elea11** [timo-a/SudoQ#11] opened 2021-09-23 10:30 UTC
Current F-Droid build 2.0.0.33 crashes on vanilla a11 with MicroG.
Guess it's Google services related (what shouldn't happen for f-droid builds). Here's a log: https://pastebin.com/t8NMJdGe 
Don't know if this has been solved in the latest build as it hasn't hit F-Droid yet.

**Comment by elea11** [comment] 2021-09-23 14:40
System language is German, additionally, English (US) is active as a secondary language, but not in use. If I change to English (US), SudoQ still crashes. Same if I remove the secondary language (if it's English or German doesn't matter).

So, it must be sth. else imho.

My bet was that it checks the language through a google framework which doesn't exist as such on my phone. But this is just a wild guess as I cannot even properly read logs^^

**Comment by sfeigl** [comment] 2021-09-23 19:02
I can confirm that the fdroid version crashes (even with Google Frameworks installed). I suppose this bug is already fixed with 2.0.4

My problem is not fixed yet and the patch above does not fix the problem neither. 

I have created a fix and might share it later.

F-Droid users can simply wait until 2.0.4 has pushed to F-Droid

**Comment by sfeigl** [comment] 2021-09-23 19:28
PR for my issue: https://github.com/timo-a/SudoQ/pull/12#issue-1005772470

**Comment by timo-a** [comment] 2021-09-25 08:48
This crash happens because I mistakenly assigned the property `language` in its own setter. Thus a the setter calls itself until a StackOverflowError happens.

https://github.com/timo-a/SudoQ/blob/4d253882193f971da3e6624b1c17e9cafb8aa9ed/sudoq-app/sudoqapp/src/main/kotlin/de/sudoq/controller/menus/preferences/LanguageSetting.kt#L13-L25

I fixed it in version 2.0.1: https://github.com/timo-a/SudoQ/commit/41830191f233a96975925ea59a7e7fb8e93a9a2f#diff-e32fd281e88777b0f40195e6b4ddf6c6e33077f26090329ab8fd057d2b08f4b1
With version 2.0.4 released f-droid users should no longer face this issue.
Because of this I consider the issue solved and close it. If you experience the same problems with 2.0.4 feel free to reopen this issue.

**Closed by timo-a** 2021-09-25 08:48 UTC
